import MemoryArtifact.Ops
import MemoryArtifact.Lemmas.PushBasic

/-!
# Three tables amendment B rests on, decided whole

Amendment B adds one entry to `Kind.offerableIn` (the hippocampus takes an offered stop), rests on the stop's row of
`Kind.targetOk` (a stop points only to a task), and rests on a stop standing in the hippocampus alone (`Kind.allowedIn`).
The audit of the candidate (audit F, finding F1) found that nothing pinned the first two beyond the entry the amendment
adds, and the check of the repair found the same of the third: a definition that admitted an offered hand-over, an offered
aside, a stop offered to the shared store, a stop pointing to any kind, or a stop held in the private store, the shared
store or the toolkit built clean. The three theorems below decide each table whole, for every log and every kind, against
a table written out here: a change to any of the three definitions that this file does not make too fails the build.
One more theorem, `offerable_not_allowed`, pins where the offer table is wider than the allowed one: a caller may offer
every edge to the shared part of the store and to the toolkit, which hold only a supersedes edge, so the other five are
refused on arrival (local check 3); narrowing `Kind.offerableIn` is left to the next version.

The tables were generated by evaluating the definitions over every pair, so they pin what the definitions say today, not
what the design record says. By the design record's ruling 13, the second version's catalogue of target kinds is this
model's own, and `Kind.targetTable` writes it out. The record's own words, its section 13 and the specification, describe
the appends in prose. A first reading of the tables against them, row by row, was made on 2026-10-02 by a reader who wrote
neither. It found rows on which the prose is silent; rows where the record's amendments toward version 2.1 are not built
here, among them a return's single pointer to its call, the nights a private framing is made from, and the page as placed;
and rows where the catalogue is narrower or wider than the prose. They are settled with the model's next version; none is
changed by amendment B.

The other definitions the amendment rests on (`numbered`, `carriesTask`, `arity`, `firstOk`, `isEntryKind`, `DaysOk`,
`LocDays`) are held by proofs that break when they change, not by a statement of their own.

`Kind.all` lists every kind (`Kind.mem_all`), none twice (`Kind.nodup_all`), 43 in all (`Kind.length_all`), and
`LogId.all` every log (`PushBasicAux.logId_mem_all`), none twice (`LogId.nodup_all`), 4 in all (`LogId.length_all`), so
that a statement about every kind and every log is decidable.
-/

namespace MemoryArtifact

/-- Every kind, each once (`Kind.nodup_all`, `Kind.length_all`): the 27 kinds without an argument and the six edge, six
return and four shelf kinds, 43 in all. -/
def Kind.all : List Kind :=
  [.night, .aside, .keep, .edge .same, .edge .continues, .edge .corrects, .edge .contradicts, .edge .supersedes,
   .edge .cites, .correction, .consolidation, .proposal, .root, .group, .page, .dayRecord, .ret .infos, .ret .span,
   .ret .nothing, .ret .refusal, .ret .digest, .ret .acknowledgement, .cursor, .notice, .answer, .framing,
   .shelf .passage, .shelf .way, .shelf .readersPage, .shelf .recipes, .heard, .tool, .question, .handOver, .stop,
   .call, .recipe, .given, .outcome, .task, .say, .filed, .policy]

/-- `Kind.all` holds every kind. -/
theorem Kind.mem_all (k : Kind) : k ∈ Kind.all := by
  cases k <;> (try (rename_i x; cases x)) <;> decide

/-- `Kind.all` lists no kind twice. -/
theorem Kind.nodup_all : Kind.all.Nodup := by decide +kernel

/-- `Kind.all` lists 43 kinds. -/
theorem Kind.length_all : Kind.all.length = 43 := by decide +kernel

/-- `LogId.all` lists no log twice. -/
theorem LogId.nodup_all : LogId.all.Nodup := by decide +kernel

/-- `LogId.all` lists 4 logs. -/
theorem LogId.length_all : LogId.all.length = 4 := by decide +kernel

/-- What a caller may offer to each log, written out: the table `Kind.offerableIn` must agree with. -/
def Kind.offerableTable : LogId → List Kind
  | .hippocampus => [.night, .correction, .consolidation, .proposal, .stop]
  | .storePrivate =>
    [.edge .same, .edge .continues, .edge .corrects, .edge .contradicts, .edge .supersedes, .edge .cites, .page,
     .dayRecord, .notice, .answer, .framing, .task]
  | .storeShared =>
    [.edge .same, .edge .continues, .edge .corrects, .edge .contradicts, .edge .supersedes, .edge .cites, .notice,
     .framing, .shelf .passage, .shelf .way, .shelf .readersPage, .shelf .recipes, .heard, .say, .policy]
  | .toolkit =>
    [.edge .same, .edge .continues, .edge .corrects, .edge .contradicts, .edge .supersedes, .edge .cites, .tool]

/-- The whole of `Kind.offerableIn`: for every log and every kind, a caller may offer the kind to the log exactly when the
table lists it. In particular the hippocampus takes an offered night, correction, consolidation, proposal and stop and no
other kind (no hand-over, no aside, no call), and no log but the hippocampus takes an offered stop. -/
theorem offerableIn_table (l : LogId) (k : Kind) : Kind.offerableIn l k = true ↔ k ∈ Kind.offerableTable l := by
  have h : ∀ l ∈ LogId.all, ∀ k ∈ Kind.all, (Kind.offerableIn l k = true ↔ k ∈ Kind.offerableTable l) := by
    decide +kernel
  exact h l (PushBasicAux.logId_mem_all l) k (Kind.mem_all k)

/-- Which kinds each log may hold, written out: the table `Kind.allowedIn` must agree with. -/
def Kind.allowedTable : LogId → List Kind
  | .hippocampus =>
    [.night, .aside, .keep, .edge .same, .edge .continues, .edge .corrects, .edge .contradicts, .edge .supersedes,
     .edge .cites, .correction, .consolidation, .proposal, .question, .handOver, .stop, .call, .recipe, .given,
     .outcome]
  | .storePrivate =>
    [.edge .same, .edge .continues, .edge .corrects, .edge .contradicts, .edge .supersedes, .edge .cites, .root,
     .group, .page, .dayRecord, .ret .infos, .ret .span, .ret .nothing, .ret .refusal, .ret .digest,
     .ret .acknowledgement, .cursor, .notice, .answer, .framing, .task]
  | .storeShared =>
    [.edge .supersedes, .notice, .framing, .shelf .passage, .shelf .way, .shelf .readersPage, .shelf .recipes, .heard,
     .say, .filed, .policy]
  | .toolkit => [.edge .supersedes, .tool]

/-- The whole of `Kind.allowedIn`: for every log and every kind, the log may hold the kind exactly when the table lists
it. In particular a stop stands in the hippocampus and in no other log. -/
theorem allowedIn_table (l : LogId) (k : Kind) : Kind.allowedIn l k = true ↔ k ∈ Kind.allowedTable l := by
  have h : ∀ l ∈ LogId.all, ∀ k ∈ Kind.all, (Kind.allowedIn l k = true ↔ k ∈ Kind.allowedTable l) := by
    decide +kernel
  exact h l (PushBasicAux.logId_mem_all l) k (Kind.mem_all k)

/-- Where the offer table is wider than the allowed one, exactly: a caller may offer to the shared part of the store and
to the toolkit every edge, and those logs hold only a supersedes edge, so the other five are refused on arrival (local
check 3, `LocEnvelope`). Everywhere else what may be offered may be held. -/
theorem offerable_not_allowed (l : LogId) (k : Kind) :
    (Kind.offerableIn l k = true ∧ Kind.allowedIn l k = false) ↔
      ((l = .storeShared ∨ l = .toolkit) ∧
        k ∈ [.edge .same, .edge .continues, .edge .corrects, .edge .contradicts, .edge .cites]) := by
  have h : ∀ l ∈ LogId.all, ∀ k ∈ Kind.all, ((Kind.offerableIn l k = true ∧ Kind.allowedIn l k = false) ↔
      ((l = .storeShared ∨ l = .toolkit) ∧
        k ∈ [.edge .same, .edge .continues, .edge .corrects, .edge .contradicts, .edge .cites])) := by
    decide +kernel
  exact h l (PushBasicAux.logId_mem_all l) k (Kind.mem_all k)

/-- The kinds an info of each kind may point to, written out: the table `Kind.targetOk` must agree with. `Kind.all` stands
for a kind that may point to any kind. -/
def Kind.targetTable : Kind → List Kind
  | .night => [.task]
  | .aside => [.aside, .call, .task]
  | .keep => Kind.all
  | .edge .same => Kind.all
  | .edge .continues =>
    [.night, .aside, .correction, .consolidation, .proposal, .notice, .answer, .framing, .shelf .passage,
     .shelf .way, .shelf .readersPage, .shelf .recipes, .heard, .tool, .question, .handOver, .stop, .task, .say,
     .filed]
  | .edge .corrects =>
    [.night, .aside, .correction, .consolidation, .proposal, .notice, .answer, .framing, .shelf .passage,
     .shelf .way, .shelf .readersPage, .shelf .recipes, .heard, .tool, .question, .handOver, .stop, .task, .say,
     .filed]
  | .edge .contradicts => Kind.all
  | .edge .supersedes => Kind.all
  | .edge .cites => Kind.all
  | .correction =>
    [.night, .aside, .correction, .consolidation, .proposal, .notice, .answer, .framing, .shelf .passage,
     .shelf .way, .shelf .readersPage, .shelf .recipes, .heard, .tool, .question, .handOver, .stop, .task, .say,
     .filed]
  | .consolidation => [.night, .aside, .task]
  | .proposal => [.notice, .framing, .shelf .passage, .shelf .way, .shelf .readersPage, .shelf .recipes, .task]
  | .root =>
    [.night, .aside, .keep, .correction, .consolidation, .proposal, .root, .group, .notice, .answer, .framing,
     .shelf .passage, .shelf .way, .shelf .readersPage, .shelf .recipes, .heard, .tool, .question, .handOver, .stop,
     .task, .say, .filed]
  | .group =>
    [.night, .aside, .correction, .consolidation, .proposal, .group, .notice, .answer, .framing, .shelf .passage,
     .shelf .way, .shelf .readersPage, .shelf .recipes, .heard, .tool, .question, .handOver, .stop, .task, .say,
     .filed]
  | .page =>
    [.notice, .answer, .framing, .shelf .passage, .shelf .way, .shelf .readersPage, .shelf .recipes, .heard, .task,
     .say]
  | .dayRecord => [.night, .root, .page]
  | .ret .infos => Kind.all
  | .ret .span => Kind.all
  | .ret .nothing => Kind.all
  | .ret .refusal => Kind.all
  | .ret .digest => Kind.all
  | .ret .acknowledgement => Kind.all
  | .cursor => [.ret .infos, .ret .span, .ret .nothing, .ret .refusal, .ret .digest, .ret .acknowledgement]
  | .notice => [.notice]
  | .answer => [.night, .question, .handOver, .call]
  | .framing => [.framing]
  | .shelf .passage => Kind.all
  | .shelf .way => Kind.all
  | .shelf .readersPage => Kind.all
  | .shelf .recipes => Kind.all
  | .heard => [.say]
  | .tool => [.tool]
  | .question => [.task]
  | .handOver => [.task]
  | .stop => [.task]
  | .call => Kind.all
  | .recipe => [.call, .task]
  | .given => [.recipe, .task]
  | .outcome => [.ret .infos, .ret .span, .ret .nothing, .ret .refusal, .ret .digest, .ret .acknowledgement, .task]
  | .task => [.shelf .passage, .shelf .way, .shelf .readersPage, .shelf .recipes]
  | .say => []
  | .filed => Kind.all
  | .policy => [.policy]

/-- The whole of `Kind.targetOk`: for every kind and every target kind, an info of the first may point to an info of the
second exactly when the table lists it. In particular a stop points only to a task. -/
theorem targetOk_table (k t : Kind) : Kind.targetOk k t = true ↔ t ∈ Kind.targetTable k := by
  have h : ∀ k ∈ Kind.all, ∀ t ∈ Kind.all, (Kind.targetOk k t = true ↔ t ∈ Kind.targetTable k) := by
    decide +kernel
  exact h k (Kind.mem_all k) t (Kind.mem_all t)

end MemoryArtifact
